# Generated by Django 5.1.6 on 2025-02-25 12:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_block_title', ckeditor.fields.RichTextField(default='none', verbose_name='First Block Title')),
                ('first_block_second_title', ckeditor.fields.RichTextField(default='none', verbose_name='First Block Second Title')),
                ('first_block_desc', ckeditor.fields.RichTextField(default='none', verbose_name='First Block')),
                ('contact_link', models.CharField(max_length=200, verbose_name='Phone url')),
            ],
            options={
                'verbose_name': 'Main Texts',
                'verbose_name_plural': 'Main Texts Block',
            },
        ),
    ]
