# Generated by Django 5.1.6 on 2025-02-25 12:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_first_block_title_maintexts_firstblocktitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintexts',
            name='secondBlockTitle',
            field=ckeditor.fields.RichTextField(default='none', verbose_name='Second Block Title'),
        ),
    ]
