# Generated by Django 5.1.6 on 2025-02-25 12:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_maintexts_secondblocktitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintexts',
            name='thirdBlockTitle',
            field=ckeditor.fields.RichTextField(default='none', verbose_name='Third Block Title'),
        ),
    ]
