# Generated by Django 5.1.6 on 2025-02-25 12:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
