# Generated by Django 5.1.6 on 2025-02-25 13:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_specialty_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintexts',
            name='consultations',
            field=ckeditor.fields.RichTextField(default='none', verbose_name='Consultations'),
        ),
    ]
