# Generated by Django 5.1.6 on 2025-02-25 13:23

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_maintexts_consultations'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.URLField(default='', verbose_name='Image')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.AddField(
            model_name='maintexts',
            name='headerSlider',
            field=ckeditor.fields.RichTextField(default='none', verbose_name='Header Slider Text'),
        ),
    ]
