# Generated by Django 5.1.6 on 2025-02-25 13:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_headerslider_maintexts_headerslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('review', ckeditor.fields.RichTextField(default='none', verbose_name='Review')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.AlterModelOptions(
            name='headerslider',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Header Slider Images'},
        ),
    ]
