# Generated by Django 5.1.6 on 2025-02-25 13:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_reviews_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintexts',
            name='reviewsHeader',
            field=ckeditor.fields.RichTextField(default='none', verbose_name='Reviews Header'),
        ),
    ]
