# Generated by Django 5.1.6 on 2025-02-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='img',
            field=models.URLField(default='', verbose_name='Photo'),
        ),
    ]
