# Generated by Django 5.1.6 on 2025-02-25 14:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_doctors_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='review',
        ),
        migrations.AddField(
            model_name='doctors',
            name='desc',
            field=ckeditor.fields.RichTextField(default='none', verbose_name='Description'),
        ),
    ]
