# Generated by Django 5.1.6 on 2025-02-25 15:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintexts',
            name='blogHeader',
            field=ckeditor.fields.RichTextField(default='none', verbose_name='Blog Header'),
        ),
    ]
