# Generated by Django 5.1.6 on 2025-02-25 15:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_maintexts_footertxt'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintexts',
            name='contactinbottom',
            field=ckeditor.fields.RichTextField(default='none', verbose_name='Contact text in bottom'),
        ),
    ]
